---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: ui
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
        containers:
        - name: ui-service
          image: bege13mot/ui-service:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: ui
